chat-format:
  info-prefix: '<dark_gray>[<dark_green>T#</dark_green>] » </dark_gray>'
  alert-prefix: '<dark_gray>[<dark_green>T#</dark_green>] » </dark_gray>'

reduced_console_messages: true

height_datapack: false

height_in_actionbar: false

min_latitude: 0.0
max_latitude: 0.0
min_longitude: 0.0
max_longitude: 0.0

passthrough_tpll: ''

terrain_offset:
  x: 0
  y: 0
  z: 0

linked_worlds:
  enabled: false
  method: 'MULTIVERSE'
  worlds:
    - name: another_world/server
      offset: 2032
    - name: current_world/server
      offset: 0
    - name: another_world/server
      offset: -2032

generate_trees: true

different_biomes: true

surface_material: GRASS_BLOCK
building_outlines_material: BRICKS
road_material: GRAY_CONCRETE_POWDER
path_material: MOSS_BLOCK

# NOTE: Do not change
config-version: 1.5